2018-11-19 13:20:23 Error: [MissingControllerException] Controller class UsersController could not be found.
Exception Attributes: array (
  'class' => 'UsersController',
  'plugin' => NULL,
)
Request URL: /cakephp/users/login
Stack Trace:
#0 /var/www/html/cakephp/app/webroot/index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2018-11-19 13:25:22 Error: [MissingControllerException] Controller class UsersController could not be found.
Exception Attributes: array (
  'class' => 'UsersController',
  'plugin' => NULL,
)
Request URL: /cakephp/users/login
Stack Trace:
#0 /var/www/html/cakephp/app/webroot/index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2018-11-19 13:25:42 Error: [MissingControllerException] Controller class UsersController could not be found.
Exception Attributes: array (
  'class' => 'UsersController',
  'plugin' => NULL,
)
Request URL: /cakephp/users/login
Stack Trace:
#0 /var/www/html/cakephp/app/webroot/index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2018-11-19 14:27:33 Error: [MissingControllerException] Controller class UsersController could not be found.
Exception Attributes: array (
  'class' => 'UsersController',
  'plugin' => NULL,
)
Request URL: /cakephp/users/login
Stack Trace:
#0 /var/www/html/cakephp/app/webroot/index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2018-11-19 14:29:59 Error: [MissingControllerException] Controller class UsersController could not be found.
Exception Attributes: array (
  'class' => 'UsersController',
  'plugin' => NULL,
)
Request URL: /cakephp/users/login
Stack Trace:
#0 /var/www/html/cakephp/app/webroot/index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2018-11-19 14:30:18 Error: [MissingControllerException] Controller class UsersController could not be found.
Exception Attributes: array (
  'class' => 'UsersController',
  'plugin' => NULL,
)
Request URL: /cakephp/users/login
Stack Trace:
#0 /var/www/html/cakephp/app/webroot/index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2018-11-19 14:33:40 Error: [MissingControllerException] Controller class UsersController could not be found.
Exception Attributes: array (
  'class' => 'UsersController',
  'plugin' => NULL,
)
Request URL: /cakephp/users/login
Stack Trace:
#0 /var/www/html/cakephp/app/webroot/index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2018-11-19 14:34:16 Error: [MissingControllerException] Controller class UsersController could not be found.
Exception Attributes: array (
  'class' => 'UsersController',
  'plugin' => NULL,
)
Request URL: /cakephp/users/login
Stack Trace:
#0 /var/www/html/cakephp/app/webroot/index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2018-11-19 14:34:44 Error: [MissingControllerException] Controller class UsersController could not be found.
Exception Attributes: array (
  'class' => 'UsersController',
  'plugin' => NULL,
)
Request URL: /cakephp/users/login
Stack Trace:
#0 /var/www/html/cakephp/app/webroot/index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2018-11-19 14:34:46 Error: [MissingControllerException] Controller class UsersController could not be found.
Exception Attributes: array (
  'class' => 'UsersController',
  'plugin' => NULL,
)
Request URL: /cakephp/users/login
Stack Trace:
#0 /var/www/html/cakephp/app/webroot/index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2018-11-19 14:39:37 Error: [CakeException] Password hasher class "BlowFish" was not found.
Request URL: /cakephp/
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Controller/Component/Auth/BaseAuthenticate.php(138): BaseAuthenticate->passwordHasher()
#1 /var/www/html/cakephp/lib/Cake/Controller/Component/Auth/FormAuthenticate.php(79): BaseAuthenticate->_findUser('test', 'test@123')
#2 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(772): FormAuthenticate->authenticate(Object(CakeRequest), Object(CakeResponse))
#3 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(612): AuthComponent->identify(Object(CakeRequest), Object(CakeResponse))
#4 /var/www/html/cakephp/app/Controller/EmployeesController.php(8): AuthComponent->login()
#5 [internal function]: EmployeesController->login()
#6 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(EmployeesController), Array)
#7 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#8 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EmployeesController), Object(CakeRequest))
#9 /var/www/html/cakephp/app/webroot/index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2018-11-19 15:05:04 Error: [CakeException] Authentication adapter "userModel" was not found.
Request URL: /cakephp/
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(695): AuthComponent->constructAuthenticate()
#1 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(305): AuthComponent->_getUser()
#2 [internal function]: AuthComponent->startup(Object(EmployeesController))
#3 /var/www/html/cakephp/lib/Cake/Utility/ObjectCollection.php(129): call_user_func_array(Array, Array)
#4 [internal function]: ObjectCollection->trigger(Object(CakeEvent))
#5 /var/www/html/cakephp/lib/Cake/Event/CakeEventManager.php(243): call_user_func(Array, Object(CakeEvent))
#6 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(683): CakeEventManager->dispatch(Object(CakeEvent))
#7 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#8 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EmployeesController), Object(CakeRequest))
#9 /var/www/html/cakephp/app/webroot/index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2018-11-19 15:05:19 Error: Fatal Error (1): Call to a member function unauthenticated() on null in [/var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php, line 350]
2018-11-19 15:05:19 Error: [FatalErrorException] Call to a member function unauthenticated() on null
Request URL: /cakephp/
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/var/www/html/c...', 350)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/var/www/html/c...', 350, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/var/www/html/c...', 350, Array)
#3 /var/www/html/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2018-11-19 17:54:50 Error: [MissingActionException] Action EmployeesController::index() could not be found.
Exception Attributes: array (
  'controller' => 'EmployeesController',
  'action' => 'index',
)
Request URL: /cakephp/employees
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EmployeesController), Object(CakeRequest))
#2 /var/www/html/cakephp/app/webroot/index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2018-11-19 18:01:25 Error: [CakeException] Unknown status code
Request URL: /cakephp/
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(797): CakeResponse->statusCode('test')
#1 /var/www/html/cakephp/app/Controller/EmployeesController.php(12): Controller->redirect('/employees/dash...', 'test')
#2 [internal function]: EmployeesController->login()
#3 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(EmployeesController), Array)
#4 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#5 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EmployeesController), Object(CakeRequest))
#6 /var/www/html/cakephp/app/webroot/index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#7 {main}
2018-11-19 18:35:27 Error: [MissingViewException] View file "Employees/view_profile.ctp" is missing.
Exception Attributes: array (
  'file' => 'Employees/view_profile.ctp',
)
Request URL: /cakephp/employees/viewProfile
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/View/View.php(470): View->_getViewFileName(NULL)
#1 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(968): View->render(NULL, NULL)
#2 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(200): Controller->render()
#3 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EmployeesController), Object(CakeRequest))
#4 /var/www/html/cakephp/app/webroot/index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2018-11-19 18:36:11 Error: [MissingViewException] View file "Employees/profile.ctp" is missing.
Exception Attributes: array (
  'file' => 'Employees/profile.ctp',
)
Request URL: /cakephp/employees/profile
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/View/View.php(470): View->_getViewFileName(NULL)
#1 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(968): View->render(NULL, NULL)
#2 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(200): Controller->render()
#3 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EmployeesController), Object(CakeRequest))
#4 /var/www/html/cakephp/app/webroot/index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2018-11-19 18:39:42 Error: [MissingActionException] Action EmployeesController::index() could not be found.
Exception Attributes: array (
  'controller' => 'EmployeesController',
  'action' => 'index',
)
Request URL: /cakephp/employees
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EmployeesController), Object(CakeRequest))
#2 /var/www/html/cakephp/app/webroot/index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2018-11-20 11:35:21 Error: Fatal Error (1): Call to a member function write() on null in [/var/www/html/cakephp/app/Controller/EmployeesController.php, line 10]
2018-11-20 11:35:21 Error: [FatalErrorException] Call to a member function write() on null
Request URL: /cakephp/
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/var/www/html/c...', 10)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/var/www/html/c...', 10, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/var/www/html/c...', 10, Array)
#3 /var/www/html/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2018-11-20 11:40:15 Error: Fatal Error (1): Call to a member function write() on null in [/var/www/html/cakephp/app/Controller/EmployeesController.php, line 10]
2018-11-20 11:40:15 Error: [FatalErrorException] Call to a member function write() on null
Request URL: /cakephp/
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/var/www/html/c...', 10)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/var/www/html/c...', 10, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/var/www/html/c...', 10, Array)
#3 /var/www/html/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2018-11-20 11:44:54 Error: Fatal Error (1): Call to a member function write() on null in [/var/www/html/cakephp/app/Controller/EmployeesController.php, line 11]
2018-11-20 11:44:54 Error: [FatalErrorException] Call to a member function write() on null
Request URL: /cakephp/
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/var/www/html/c...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/var/www/html/c...', 11, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/var/www/html/c...', 11, Array)
#3 /var/www/html/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2018-11-20 11:50:25 Error: Fatal Error (1): Call to a member function write() on null in [/var/www/html/cakephp/app/Controller/EmployeesController.php, line 10]
2018-11-20 11:50:25 Error: [FatalErrorException] Call to a member function write() on null
Request URL: /cakephp/
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/var/www/html/c...', 10)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/var/www/html/c...', 10, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/var/www/html/c...', 10, Array)
#3 /var/www/html/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2018-11-20 11:52:36 Error: [PDOException] SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') AS  `Employee__manager_name` FROM `bestsellers`.`employees` AS `Employee`   WH' at line 1
Request URL: /cakephp/
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Model/Datasource/DboSource.php(489): PDOStatement->execute(Array)
#1 /var/www/html/cakephp/lib/Cake/Model/Datasource/DboSource.php(455): DboSource->_execute('SELECT `Employe...', Array)
#2 /var/www/html/cakephp/lib/Cake/Model/Datasource/DboSource.php(702): DboSource->execute('SELECT `Employe...', Array, Array)
#3 /var/www/html/cakephp/lib/Cake/Model/Datasource/DboSource.php(1213): DboSource->fetchAll('SELECT `Employe...', false)
#4 /var/www/html/cakephp/lib/Cake/Model/Model.php(3040): DboSource->read(Object(Employee), Array)
#5 /var/www/html/cakephp/lib/Cake/Model/Model.php(3012): Model->_readDataSource('first', Array)
#6 /var/www/html/cakephp/lib/Cake/Controller/Component/Auth/BaseAuthenticate.php(130): Model->find('first', Array)
#7 /var/www/html/cakephp/lib/Cake/Controller/Component/Auth/FormAuthenticate.php(79): BaseAuthenticate->_findUser('test', 'test@123')
#8 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(772): FormAuthenticate->authenticate(Object(CakeRequest), Object(CakeResponse))
#9 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(612): AuthComponent->identify(Object(CakeRequest), Object(CakeResponse))
#10 /var/www/html/cakephp/app/Controller/EmployeesController.php(8): AuthComponent->login()
#11 [internal function]: EmployeesController->login()
#12 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(EmployeesController), Array)
#13 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#14 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EmployeesController), Object(CakeRequest))
#15 /var/www/html/cakephp/app/webroot/index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#16 {main}
2018-11-20 11:58:47 Error: Fatal Error (1): Call to a member function write() on null in [/var/www/html/cakephp/app/Controller/EmployeesController.php, line 11]
2018-11-20 11:58:47 Error: [FatalErrorException] Call to a member function write() on null
Request URL: /cakephp/
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/var/www/html/c...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/var/www/html/c...', 11, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/var/www/html/c...', 11, Array)
#3 /var/www/html/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2018-11-20 12:06:35 Error: Fatal Error (1): Call to a member function write() on null in [/var/www/html/cakephp/app/Controller/EmployeesController.php, line 11]
2018-11-20 12:06:35 Error: [FatalErrorException] Call to a member function write() on null
Request URL: /cakephp/
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/var/www/html/c...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/var/www/html/c...', 11, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/var/www/html/c...', 11, Array)
#3 /var/www/html/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2018-11-20 12:08:10 Error: Fatal Error (1): Call to a member function write() on null in [/var/www/html/cakephp/app/Controller/EmployeesController.php, line 11]
2018-11-20 12:08:10 Error: [FatalErrorException] Call to a member function write() on null
Request URL: /cakephp/
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/var/www/html/c...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/var/www/html/c...', 11, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/var/www/html/c...', 11, Array)
#3 /var/www/html/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2018-11-20 12:14:31 Error: Fatal Error (1): Call to a member function write() on null in [/var/www/html/cakephp/app/Controller/EmployeesController.php, line 12]
2018-11-20 12:14:31 Error: [FatalErrorException] Call to a member function write() on null
Request URL: /cakephp/
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/var/www/html/c...', 12)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/var/www/html/c...', 12, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/var/www/html/c...', 12, Array)
#3 /var/www/html/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2018-11-20 12:17:52 Error: Fatal Error (1): Call to a member function write() on null in [/var/www/html/cakephp/app/Controller/EmployeesController.php, line 12]
2018-11-20 12:17:52 Error: [FatalErrorException] Call to a member function write() on null
Request URL: /cakephp/
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/var/www/html/c...', 12)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/var/www/html/c...', 12, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/var/www/html/c...', 12, Array)
#3 /var/www/html/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2018-11-20 12:18:02 Error: Fatal Error (1): Call to a member function write() on null in [/var/www/html/cakephp/app/Controller/EmployeesController.php, line 12]
2018-11-20 12:18:02 Error: [FatalErrorException] Call to a member function write() on null
Request URL: /cakephp/
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/var/www/html/c...', 12)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/var/www/html/c...', 12, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/var/www/html/c...', 12, Array)
#3 /var/www/html/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2018-11-20 12:20:09 Error: Fatal Error (1): Call to a member function write() on null in [/var/www/html/cakephp/app/Controller/EmployeesController.php, line 12]
2018-11-20 12:20:09 Error: [FatalErrorException] Call to a member function write() on null
Request URL: /cakephp/
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/var/www/html/c...', 12)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/var/www/html/c...', 12, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/var/www/html/c...', 12, Array)
#3 /var/www/html/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2018-11-20 12:25:08 Error: Fatal Error (1): Call to a member function write() on null in [/var/www/html/cakephp/app/Controller/EmployeesController.php, line 12]
2018-11-20 12:25:08 Error: [FatalErrorException] Call to a member function write() on null
Request URL: /cakephp/
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/var/www/html/c...', 12)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/var/www/html/c...', 12, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/var/www/html/c...', 12, Array)
#3 /var/www/html/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2018-11-20 12:29:41 Error: Fatal Error (1): Call to a member function User() on null in [/var/www/html/cakephp/app/Controller/EmployeesController.php, line 11]
2018-11-20 12:29:41 Error: [FatalErrorException] Call to a member function User() on null
Request URL: /cakephp/
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/var/www/html/c...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/var/www/html/c...', 11, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/var/www/html/c...', 11, Array)
#3 /var/www/html/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2018-11-20 12:29:51 Error: Fatal Error (1): Call to a member function User() on null in [/var/www/html/cakephp/app/Controller/EmployeesController.php, line 11]
2018-11-20 12:29:51 Error: [FatalErrorException] Call to a member function User() on null
Request URL: /cakephp/
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/var/www/html/c...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/var/www/html/c...', 11, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/var/www/html/c...', 11, Array)
#3 /var/www/html/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2018-11-20 12:30:00 Error: Fatal Error (1): Call to a member function User() on null in [/var/www/html/cakephp/app/Controller/EmployeesController.php, line 11]
2018-11-20 12:30:00 Error: [FatalErrorException] Call to a member function User() on null
Request URL: /cakephp/
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/var/www/html/c...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/var/www/html/c...', 11, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/var/www/html/c...', 11, Array)
#3 /var/www/html/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2018-11-20 12:30:08 Error: Fatal Error (1): Call to a member function User() on null in [/var/www/html/cakephp/app/Controller/EmployeesController.php, line 11]
2018-11-20 12:30:08 Error: [FatalErrorException] Call to a member function User() on null
Request URL: /cakephp/
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/var/www/html/c...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/var/www/html/c...', 11, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/var/www/html/c...', 11, Array)
#3 /var/www/html/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2018-11-20 12:34:41 Error: Fatal Error (1): Call to a member function write() on null in [/var/www/html/cakephp/app/Controller/EmployeesController.php, line 11]
2018-11-20 12:34:41 Error: [FatalErrorException] Call to a member function write() on null
Request URL: /cakephp/
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/var/www/html/c...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/var/www/html/c...', 11, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/var/www/html/c...', 11, Array)
#3 /var/www/html/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2018-11-20 12:35:54 Error: [PDOException] SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') AS  `Employee__manager_name` FROM `bestsellers`.`employees` AS `Employee`   WH' at line 1
Request URL: /cakephp/
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Model/Datasource/DboSource.php(489): PDOStatement->execute(Array)
#1 /var/www/html/cakephp/lib/Cake/Model/Datasource/DboSource.php(455): DboSource->_execute('SELECT `Employe...', Array)
#2 /var/www/html/cakephp/lib/Cake/Model/Datasource/DboSource.php(702): DboSource->execute('SELECT `Employe...', Array, Array)
#3 /var/www/html/cakephp/lib/Cake/Model/Datasource/DboSource.php(1213): DboSource->fetchAll('SELECT `Employe...', false)
#4 /var/www/html/cakephp/lib/Cake/Model/Model.php(3040): DboSource->read(Object(Employee), Array)
#5 /var/www/html/cakephp/lib/Cake/Model/Model.php(3012): Model->_readDataSource('first', Array)
#6 /var/www/html/cakephp/lib/Cake/Controller/Component/Auth/BaseAuthenticate.php(130): Model->find('first', Array)
#7 /var/www/html/cakephp/lib/Cake/Controller/Component/Auth/FormAuthenticate.php(79): BaseAuthenticate->_findUser('test', 'test@123')
#8 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(772): FormAuthenticate->authenticate(Object(CakeRequest), Object(CakeResponse))
#9 /var/www/html/cakephp/lib/Cake/Controller/Component/AuthComponent.php(612): AuthComponent->identify(Object(CakeRequest), Object(CakeResponse))
#10 /var/www/html/cakephp/app/Controller/EmployeesController.php(8): AuthComponent->login()
#11 [internal function]: EmployeesController->login()
#12 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs(Object(EmployeesController), Array)
#13 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#14 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EmployeesController), Object(CakeRequest))
#15 /var/www/html/cakephp/app/webroot/index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#16 {main}
2018-11-20 12:36:05 Error: Fatal Error (1): Call to a member function write() on null in [/var/www/html/cakephp/app/Controller/EmployeesController.php, line 11]
2018-11-20 12:36:05 Error: [FatalErrorException] Call to a member function write() on null
Request URL: /cakephp/
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/var/www/html/c...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/var/www/html/c...', 11, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/var/www/html/c...', 11, Array)
#3 /var/www/html/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2018-11-20 12:37:10 Error: Fatal Error (1): Call to a member function write() on null in [/var/www/html/cakephp/app/Controller/EmployeesController.php, line 11]
2018-11-20 12:37:10 Error: [FatalErrorException] Call to a member function write() on null
Request URL: /cakephp/
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/var/www/html/c...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/var/www/html/c...', 11, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/var/www/html/c...', 11, Array)
#3 /var/www/html/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2018-11-20 12:39:22 Error: Fatal Error (1): Call to undefined method AuthComponent::write() in [/var/www/html/cakephp/app/Controller/EmployeesController.php, line 11]
2018-11-20 12:39:22 Error: [FatalErrorException] Call to undefined method AuthComponent::write()
Request URL: /cakephp/
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Call to undefin...', '/var/www/html/c...', 11)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', '/var/www/html/c...', 11, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', '/var/www/html/c...', 11, Array)
#3 /var/www/html/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2018-11-20 12:47:31 Error: Fatal Error (1): Call to a member function write() on null in [/var/www/html/cakephp/app/Controller/EmployeesController.php, line 10]
2018-11-20 12:47:31 Error: [FatalErrorException] Call to a member function write() on null
Request URL: /cakephp/
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/var/www/html/c...', 10)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/var/www/html/c...', 10, Array)
#2 /var/www/html/cakephp/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/var/www/html/c...', 10, Array)
#3 /var/www/html/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2018-11-20 18:48:01 Error: [MissingHelperException] Helper class testMeHelper could not be found.
Exception Attributes: array (
  'class' => 'testMeHelper',
  'plugin' => false,
)
Request URL: /cakephp/employees/dashboard
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/View/HelperCollection.php(63): HelperCollection->load('testMe')
#1 /var/www/html/cakephp/lib/Cake/View/View.php(858): HelperCollection->__isset('testMe')
#2 /var/www/html/cakephp/app/View/Employees/dashboard.ctp(1): View->__get('testMe')
#3 /var/www/html/cakephp/lib/Cake/View/View.php(971): include('/var/www/html/c...')
#4 /var/www/html/cakephp/lib/Cake/View/View.php(933): View->_evaluate('/var/www/html/c...', Array)
#5 /var/www/html/cakephp/lib/Cake/View/View.php(473): View->_render('/var/www/html/c...')
#6 /var/www/html/cakephp/lib/Cake/Controller/Controller.php(968): View->render(NULL, NULL)
#7 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(200): Controller->render()
#8 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EmployeesController), Object(CakeRequest))
#9 /var/www/html/cakephp/app/webroot/index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2018-11-20 18:48:41 Error: [MissingActionException] Action EmployeesController::rofile() could not be found.
Exception Attributes: array (
  'controller' => 'EmployeesController',
  'action' => 'rofile',
)
Request URL: /cakephp/employees/rofile
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EmployeesController), Object(CakeRequest))
#2 /var/www/html/cakephp/app/webroot/index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2018-11-20 18:49:19 Error: [MissingActionException] Action EmployeesController::rofile() could not be found.
Exception Attributes: array (
  'controller' => 'EmployeesController',
  'action' => 'rofile',
)
Request URL: /cakephp/employees/rofile
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EmployeesController), Object(CakeRequest))
#2 /var/www/html/cakephp/app/webroot/index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2018-11-20 18:49:27 Error: [MissingActionException] Action EmployeesController::index() could not be found.
Exception Attributes: array (
  'controller' => 'EmployeesController',
  'action' => 'index',
)
Request URL: /cakephp/employees
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EmployeesController), Object(CakeRequest))
#2 /var/www/html/cakephp/app/webroot/index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2018-11-20 18:49:36 Error: [MissingActionException] Action EmployeesController::rofile() could not be found.
Exception Attributes: array (
  'controller' => 'EmployeesController',
  'action' => 'rofile',
)
Request URL: /cakephp/employees/rofile
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EmployeesController), Object(CakeRequest))
#2 /var/www/html/cakephp/app/webroot/index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2018-11-20 18:49:47 Error: [MissingActionException] Action EmployeesController::rofile() could not be found.
Exception Attributes: array (
  'controller' => 'EmployeesController',
  'action' => 'rofile',
)
Request URL: /cakephp/employees/rofile
Stack Trace:
#0 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 /var/www/html/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EmployeesController), Object(CakeRequest))
#2 /var/www/html/cakephp/app/webroot/index.php(118): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
